BIT_TEXTS = {
    "Status 1": {
        0: "Standby",
        1: "Reserved",
        2: "Operation",
        3: "Reserved",
        4: "Reserved",
        5: "Reserved",
        6: "Fault",
        7: "Reserved",
    },

    # Sonderfall: nur Bit0 relevant, aber Wert unterscheidet sich nach 0/1
    "Status 3": {
        0: "Not off-grid",   # Bit0 = 0
        1: "Off-grid",       # Bit0 = 1
    },

    "BMS1 Fault1": {
        0: "Cell Over Voltage",
        1: "Cell Under Voltage",
        2: "Pack Over Voltage",
        3: "Pack Under Voltage",
        4: "Charge Overcurrent",
        5: "Discharge Overcurrent",
        6: "High Temperature",
        7: "Low Temperature",
        8: "BMS Comm Lost",
        9: "Balancer Fault",
        10: "Internal Error",
        11: "Fuse Fault",
        12: "Relay Fault",
        13: "EEPROM Error",
        14: "Reserved",
        15: "Reserved",
    },

    "Alarm 1": {
        0: "Input string voltage is high",
        1: "DC arc fault",
        2: "String reverse connection",
        3: "Reserved",
        4: "Reserved",
        5: "Reserved",
        6: "Reserved",
        7: "Grid power outage",
        8: "Abnormal power grid voltage",
        9: "Reserved",
        10: "Reserved",
        11: "Abnormal power grid frequency",
        12: "Reserved",
        13: "Reserved",
        14: "Output overcurrent",
        15: "The DC component of the output current is too large",
    },

    "Alarm 2": {
        0: "Abnormal residual current",
        1: "System grounding abnormality",
        2: "Low insulation resistance",
        3: "Temperature is too high",
        4: "Reserved",
        5: "Reserved",
        6: "Reserved",
        7: "Reserved",
        8: "Reserved",
        9: "Energy storage equipment abnormality",
        10: "Isolated island",
        11: "Reserved",
        12: "Reserved",
        13: "Reserved",
        14: "Off-grid output overload",
        15: "Reserved",
    },

    "Alarm 3": {
        0: "Reserved",
        1: "Reserved",
        2: "Reserved",
        3: "External fan abnormality",
        4: "Energy storage reverse connection",
        5: "Reserved",
        6: "Reserved",
        7: "Reserved",
        8: "Reserved",
        9: "Meter Lost",
        10: "BMS Lost",
        11: "Reserved",
        12: "Reserved",
        13: "Reserved",
        14: "Reserved",
        15: "Reserved",
    },
}
